# 应用的全局配置信息
server:
  port: 8089

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
# mybatis mapper关联
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package=cn: com.tourguide.model